[workspace]
members = ["packages/reactive"]

[package]
name = "xframe"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
xframe-reactive = { path = "packages/reactive" }
