[package]
name = "xframe-web"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
ahash = "0.8"
indexmap = "1.9"
js-sys = "0.3"
smallvec = "1.10"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "AddEventListenerOptions",
    "CharacterData",
    "Comment",
    "Document",
    "DocumentFragment",
    "DomTokenList",
    "Element",
    "Event",
    "HtmlTemplateElement",
    "Text",
    "Window",
]

[dependencies.xframe-core]
path = "../core"

[dependencies.xframe-reactive]
path = "../reactive"
