[package]
name = "xframe-web"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "AddEventListenerOptions",
    "CharacterData",
    "Document",
    "DomTokenList",
    "Element",
    "Event",
    "HtmlElement",
    "Text",
    "Window",
]

[dependencies.xframe-core]
path = "../core"

[dependencies.xframe-reactive]
path = "../reactive"

[build-dependencies]
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[build-dependencies.web-types]
path = "../web-types"
features = ["preset"]
