mod extra;

use crate::Result;
use std::{env, io::Write, path::Path, process::Command};

pub fn expand_web_types(path: &Path) -> Result<()> {
    let content = extra::expand(&web_types::load_preset()).to_string();
    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(b"// This file is automatically @generated by xframe-extra.\n")?;
    f.write_all(content.as_bytes())?;
    if env::var("PROFILE").unwrap() == "debug" {
        Command::new(env::var("CARGO").unwrap())
            .arg("fmt")
            .arg("--")
            .arg(path)
            .output()?;
    }
    Ok(())
}
