[package]
name = "xframe-reactive"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["fxhash"]
fxhash = ["dep:rustc-hash"]

[dependencies]
indexmap = "1.9"
slotmap = "1.0"

[dependencies.rustc-hash]
version = "1.1"
optional = true

[dependencies.smallvec]
version = "1.10"
features = ["union"]
