[package]
name = "xframe-reactive"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = []
ahash = ["dep:ahash"]

[dependencies]
indexmap = "1.9"
slotmap = "1.0"

[dependencies.ahash]
version = "0.8"
optional = true
