#[path = "web_types.rs"]
mod web_types_;

use crate::Result;
use std::{env, io::Write, path::Path, process::Command};

pub fn expand_web_types(path: &Path) -> Result<()> {
    let content = web_types_::expand(&web_types::load_preset()).to_string();
    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(b"// This file is automatically @generated by web-types.\n")?;
    f.write_all(content.as_bytes())?;
    if matches!(env::var("WEB_TYPES_FMT").ok().as_deref(), Some("1")) {
        Command::new(env::var("CARGO").unwrap())
            .arg("fmt")
            .arg("--")
            .arg(path)
            .output()?;
    }
    Ok(())
}
