#[path = "web_types.rs"]
mod web_types_;

use crate::Result;
use std::{io::Write, path::Path};

pub fn expand_web_types(path: &Path) -> Result<()> {
    let content = web_types_::expand(&web_types::load_preset()).to_string();
    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(b"// This file is automatically @generated by web-types.\n")?;
    f.write_all(content.as_bytes())?;
    Ok(())
}
