[package]
name = "xframe-extra"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["full"]
full = ["elements", "attributes", "events"]
elements = [
    "web-sys/HtmlAnchorElement",
    "web-sys/HtmlAreaElement",
    "web-sys/HtmlAudioElement",
    "web-sys/HtmlBaseElement",
    "web-sys/HtmlBodyElement",
    "web-sys/HtmlBrElement",
    "web-sys/HtmlButtonElement",
    "web-sys/HtmlCanvasElement",
    "web-sys/HtmlDListElement",
    "web-sys/HtmlDataElement",
    "web-sys/HtmlDataListElement",
    "web-sys/HtmlDetailsElement",
    "web-sys/HtmlDialogElement",
    "web-sys/HtmlDivElement",
    "web-sys/HtmlEmbedElement",
    "web-sys/HtmlFieldSetElement",
    "web-sys/HtmlFormElement",
    "web-sys/HtmlHeadElement",
    "web-sys/HtmlHeadingElement",
    "web-sys/HtmlHrElement",
    "web-sys/HtmlHtmlElement",
    "web-sys/HtmlIFrameElement",
    "web-sys/HtmlImageElement",
    "web-sys/HtmlInputElement",
    "web-sys/HtmlLabelElement",
    "web-sys/HtmlLegendElement",
    "web-sys/HtmlLiElement",
    "web-sys/HtmlLinkElement",
    "web-sys/HtmlMapElement",
    "web-sys/HtmlMenuElement",
    "web-sys/HtmlMenuItemElement",
    "web-sys/HtmlMetaElement",
    "web-sys/HtmlMeterElement",
    "web-sys/HtmlModElement",
    "web-sys/HtmlOListElement",
    "web-sys/HtmlObjectElement",
    "web-sys/HtmlOptGroupElement",
    "web-sys/HtmlOptionElement",
    "web-sys/HtmlOutputElement",
    "web-sys/HtmlParagraphElement",
    "web-sys/HtmlParamElement",
    "web-sys/HtmlPictureElement",
    "web-sys/HtmlPreElement",
    "web-sys/HtmlProgressElement",
    "web-sys/HtmlQuoteElement",
    "web-sys/HtmlScriptElement",
    "web-sys/HtmlSelectElement",
    "web-sys/HtmlSlotElement",
    "web-sys/HtmlSourceElement",
    "web-sys/HtmlSpanElement",
    "web-sys/HtmlStyleElement",
    "web-sys/HtmlTableCaptionElement",
    "web-sys/HtmlTableCellElement",
    "web-sys/HtmlTableColElement",
    "web-sys/HtmlTableElement",
    "web-sys/HtmlTableRowElement",
    "web-sys/HtmlTableSectionElement",
    "web-sys/HtmlTemplateElement",
    "web-sys/HtmlTextAreaElement",
    "web-sys/HtmlTimeElement",
    "web-sys/HtmlTitleElement",
    "web-sys/HtmlTrackElement",
    "web-sys/HtmlUListElement",
    "web-sys/HtmlVideoElement",

    "web-sys/SvgAnimateElement",
    "web-sys/SvgAnimateMotionElement",
    "web-sys/SvgAnimateTransformElement",
    "web-sys/SvgAnimationElement",
    "web-sys/SvgCircleElement",
    "web-sys/SvgClipPathElement",
    "web-sys/SvgComponentTransferFunctionElement",
    "web-sys/SvgDefsElement",
    "web-sys/SvgDescElement",
    "web-sys/SvgEllipseElement",
    "web-sys/SvgFilterElement",
    "web-sys/SvgForeignObjectElement",
    "web-sys/SvgGeometryElement",
    "web-sys/SvgGradientElement",
    "web-sys/SvgGraphicsElement",
    "web-sys/SvgImageElement",
    "web-sys/SvgLineElement",
    "web-sys/SvgLinearGradientElement",
    "web-sys/SvgMarkerElement",
    "web-sys/SvgMaskElement",
    "web-sys/SvgMetadataElement",
    "web-sys/SvgPathElement",
    "web-sys/SvgPatternElement",
    "web-sys/SvgPolygonElement",
    "web-sys/SvgPolylineElement",
    "web-sys/SvgRadialGradientElement",
    "web-sys/SvgRectElement",
    "web-sys/SvgScriptElement",
    "web-sys/SvgSetElement",
    "web-sys/SvgStopElement",
    "web-sys/SvgStyleElement",
    "web-sys/SvgSwitchElement",
    "web-sys/SvgSymbolElement",
    "web-sys/SvgTextContentElement",
    "web-sys/SvgTextElement",
    "web-sys/SvgTextPathElement",
    "web-sys/SvgTextPositioningElement",
    "web-sys/SvgTitleElement",
    "web-sys/SvgUseElement",
    "web-sys/SvgViewElement",
    "web-sys/SvgaElement",
    "web-sys/SvgfeBlendElement",
    "web-sys/SvgfeColorMatrixElement",
    "web-sys/SvgfeComponentTransferElement",
    "web-sys/SvgfeCompositeElement",
    "web-sys/SvgfeConvolveMatrixElement",
    "web-sys/SvgfeDiffuseLightingElement",
    "web-sys/SvgfeDisplacementMapElement",
    "web-sys/SvgfeDistantLightElement",
    "web-sys/SvgfeDropShadowElement",
    "web-sys/SvgfeFloodElement",
    "web-sys/SvgfeFuncAElement",
    "web-sys/SvgfeFuncBElement",
    "web-sys/SvgfeFuncGElement",
    "web-sys/SvgfeFuncRElement",
    "web-sys/SvgfeGaussianBlurElement",
    "web-sys/SvgfeImageElement",
    "web-sys/SvgfeMergeElement",
    "web-sys/SvgfeMergeNodeElement",
    "web-sys/SvgfeMorphologyElement",
    "web-sys/SvgfeOffsetElement",
    "web-sys/SvgfePointLightElement",
    "web-sys/SvgfeSpecularLightingElement",
    "web-sys/SvgfeSpotLightElement",
    "web-sys/SvgfeTileElement",
    "web-sys/SvgfeTurbulenceElement",
    "web-sys/SvggElement",
    "web-sys/SvgmPathElement",
    "web-sys/SvgsvgElement",
    "web-sys/SvgtSpanElement",
]

attributes = ["elements"]
events = [
    "elements",
    "web-sys/AnimationEvent",
    "web-sys/BeforeUnloadEvent",
    "web-sys/ClipboardEvent",
    "web-sys/CompositionEvent",
    "web-sys/DragEvent",
    "web-sys/ErrorEvent",
    "web-sys/Event",
    "web-sys/FocusEvent",
    "web-sys/GamepadEvent",
    "web-sys/HashChangeEvent",
    "web-sys/InputEvent",
    "web-sys/KeyboardEvent",
    "web-sys/MediaEncryptedEvent",
    "web-sys/MessageEvent",
    "web-sys/MouseEvent",
    "web-sys/PageTransitionEvent",
    "web-sys/PointerEvent",
    "web-sys/PopStateEvent",
    "web-sys/ProgressEvent",
    "web-sys/PromiseRejectionEvent",
    "web-sys/SecurityPolicyViolationEvent",
    "web-sys/StorageEvent",
    "web-sys/SubmitEvent",
    "web-sys/TouchEvent",
    "web-sys/TransitionEvent",
    "web-sys/UiEvent",
    "web-sys/WheelEvent",
]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = ["Event", "Node"]

[dependencies.xframe-core]
path = "../core"

[dependencies.xframe-reactive]
path = "../reactive"

[dependencies.xframe-web]
path = "../web"

[build-dependencies]
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"

[build-dependencies.syn]
version = "1.0"
default-features = false
features = ["printing"]

[build-dependencies.web-types]
path = "../web-types"
features = ["preset"]
